# Generated by Django 5.2.14 on 2026-07-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaItem",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nome_categoria", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "categoria_item",
            },
        ),
        migrations.CreateModel(
            name="DiaCardapio",
            fields=[
                ("id_dia", models.AutoField(primary_key=True, serialize=False)),
                ("data_dia", models.DateTimeField()),
                ("nome_dia", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "dia_cardapio",
            },
        ),
        migrations.CreateModel(
            name="ItemCardapio",
            fields=[
                ("id_item", models.AutoField(primary_key=True, serialize=False)),
                ("nome_item", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "item_cardapio",
            },
        ),
        migrations.CreateModel(
            name="Refeicao",
            fields=[
                ("id_refeicao", models.AutoField(primary_key=True, serialize=False)),
                ("nome_refeicao", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "refeicao",
            },
        ),
        migrations.CreateModel(
            name="SemanaCardapio",
            fields=[
                ("id_semana", models.AutoField(primary_key=True, serialize=False)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
            ],
            options={
                "db_table": "semana_cardapio",
            },
        ),
        migrations.CreateModel(
            name="Cardapio",
            fields=[
                ("id_cardapio", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        db_column="id_categoria",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.categoriaitem",
                    ),
                ),
                (
                    "id_dia",
                    models.ForeignKey(
                        db_column="id_dia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.diacardapio",
                    ),
                ),
                (
                    "id_item",
                    models.ForeignKey(
                        db_column="id_item",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.itemcardapio",
                    ),
                ),
                (
                    "id_refeicao",
                    models.ForeignKey(
                        db_column="id_refeicao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardapio.refeicao",
                    ),
                ),
            ],
            options={
                "db_table": "cardapio",
            },
        ),
        migrations.AddField(
            model_name="diacardapio",
            name="id_semana",
            field=models.ForeignKey(
                db_column="id_semana",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dias",
                to="cardapio.semanacardapio",
            ),
        ),
    ]
