# Generated by Django 5.2.6 on 2026-07-27 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': '3. Categorias',
                'db_table': 'categoria_item',
            },
        ),
        migrations.CreateModel(
            name='DiaCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dia', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': '1. Dias (Cardápio Diário)',
                'db_table': 'dia_cardapio',
                'ordering': ['-data_dia'],
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': '4. Itens do Cardápio',
                'db_table': 'item_cardapio',
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_refeicao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': '2. Refeições',
                'db_table': 'refeicao',
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.categoriaitem')),
                ('id_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.diacardapio')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.itemcardapio')),
                ('id_refeicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.refeicao')),
            ],
            options={
                'db_table': 'cardapio',
                'constraints': [models.UniqueConstraint(fields=('id_dia', 'id_refeicao', 'id_categoria', 'id_item'), name='unique_cardapio_completo')],
            },
        ),
    ]
