# Generated by Django 5.2.6 on 2026-07-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria_item',
            },
        ),
        migrations.CreateModel(
            name='DiaCardapio',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('data_dia', models.DateField(unique=True, verbose_name='Data do Dia')),
            ],
            options={
                'db_table': 'dia_cardapio',
                'ordering': ['-data_dia'],
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'item_cardapio',
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id_refeicao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_refeicao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'refeicao',
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id_cardapio', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='cardapio.categoriaitem')),
                ('id_dia', models.ForeignKey(db_column='id_dia', on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='cardapio.diacardapio')),
                ('id_item', models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.CASCADE, to='cardapio.itemcardapio')),
                ('id_refeicao', models.ForeignKey(db_column='id_refeicao', on_delete=django.db.models.deletion.CASCADE, to='cardapio.refeicao')),
            ],
            options={
                'db_table': 'cardapio',
            },
        ),
    ]
